name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build IRC chat bridge bot
      run: |
        echo "Building IRC chat bridge bot..."
        echo test, and deploy your project.

